---
- name: Determine latest postgresql jdbc driver version.
  script: postgres_jdbc_find_latest_verion.py
  register: postgres_jdbc_download_link

- name: Download postgresql jdbc driver.
  get_url:
    url: "{{ postgres_jdbc_download_link.stdout }}"
    dest: "/opt/{{ tomcat_name }}/lib"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_user }}"
    mode: 0440
  notify:
    - restart tomcat
